export default [
  'american post-rock',
  'anti-folk',
  'arab metal',
  'athens indie',
  'australian alternative rock',
  'australian dance',
  'australian electropop',
  'australian metal',
  'australian post-rock',
  'australian psych',
  'australian rock',
  'austrian metal',
  'belgian indie rock',
  'belgian new wave',
  'belgian post-rock',
  'belgian rock',
  'birmingham metal',
  'boston metal',
  'boston rock',
  'boy band',
  'brazilian groove metal',
  'brazilian hardcore',
  'brazilian metal',
  'brazilian punk',
  'brazilian rock',
  'brazilian thrash metal',
  'brighton indie',
  'bristol indie',
  'british alternative rock',
  'british black metal',
  'british blues',
  'british invasion',
  'british post-rock',
  'british soul',
  'buffalo ny indie',
  'c86',
  'california hardcore',
  'canadian electropop',
  'canadian indie',
  'canadian metal',
  'canadian pop',
  'canadian rock',
  'canadian singer-songwriter',
  'candy pop',
  'chapman stick',
  'classic canadian rock',
  'complextro',
  'cosmic american',
  'dalarna indie',
  'danish alternative rock',
  'danish metal',
  'danish rock',
  'detroit rock',
  'dissonant death metal',
  'dutch indie',
  'dutch metal',
  'dutch pop',
  'dutch rock',
  'early us punk',
  'east coast hip hop',
  'ecm-style jazz',
  'ectofolk',
  'english indie rock',
  'finnish alternative rock',
  'finnish death metal',
  'finnish doom metal',
  'finnish hard rock',
  'finnish melodeath',
  'finnish metal',
  'finnish power metal',
  'finnish progressive metal',
  'florida death metal',
  'french black metal',
  'french death metal',
  'french metal',
  'french post-rock',
  'french shoegaze',
  'gaian doom',
  'german alternative rock',
  'german dnb',
  'german hard rock',
  'german heavy metal',
  'german metal',
  'german pagan metal',
  'german power metal',
  'german rock',
  'german thrash metal',
  'girl group',
  'granada indie',
  'greek metal',
  'hi-nrg',
  'hungarian black metal',
  'hungarian metal',
  'hurdy-gurdy',
  'icelandic experimental',
  'icelandic pop',
  'icelandic post-punk',
  'icelandic rock',
  'icelandic singer-songwriter',
  'indian fusion',
  'irish rock',
  'irish singer-songwriter',
  'israeli metal',
  'italian disco',
  'italian gothic metal',
  'italian gothic',
  'italian metal',
  'italian power metal',
  'jangle pop',
  'japanese classical',
  'japanese contemporary classical',
  'japanese post-rock',
  'japanese soundtrack',
  'korean instrumental',
  'laboratorio',
  'lancashire indie',
  'lapland metal',
  'leicester indie',
  'magyar alternative',
  'manchester indie',
  'memphis soul',
  'merseybeat',
  'metal mineiro',
  'mexican classic rock',
  'mexican metal',
  'minneapolis sound',
  'musica aragonesa',
  'neue deutsche harte',
  'nightrun',
  'ninja',
  'nordic folk metal',
  'nordic post-rock',
  'northern irish indie',
  'northern soul',
  'norwegian black metal',
  'norwegian metal',
  'norwegian pop',
  'nova mpb',
  'nyhc',
  'nz metal',
  'nz pop',
  'one-person band',
  'oriental metal',
  'oxford indie',
  'paisley underground',
  'palm desert scene',
  'philly indie',
  'pixie',
  'polish post-rock',
  'quebec indie',
  'queens hip hop',
  'reading indie',
  'riot grrrl',
  'rock en espanol',
  'rune folk',
  'russian folk metal',
  'russian metal',
  'russian post-rock',
  'russian rave',
  'scottish indie',
  'scottish new wave',
  'scottish rock',
  'seattle indie',
  'seattle metal',
  'sheffield indie',
  'slavic metal',
  'slc indie',
  'south african rock',
  'southern soul',
  'spanish indie pop',
  'spanish rock',
  'speedrun',
  'swamp rock',
  'swedish alternative rock',
  'swedish death metal',
  'swedish electropop',
  'swedish garage rock',
  'swedish hard rock',
  'swedish indie pop',
  'swedish indie rock',
  'swedish melodeath',
  'swedish melodic rock',
  'swedish metal',
  'swedish pop',
  'swedish power metal',
  'swedish progressive metal',
  'swedish synth',
  'swedish synthpop',
  'swiss alternative rock',
  'swiss black metal',
  'swiss metal',
  'swiss rock',
  'texas blues',
  'texas metal',
  'tucson indie',
  'tucson indie',
  'uk doom metal',
  'uk metalcore',
  'uk post-punk',
  'uk post-punk',
  'us power metal',
  'vancouver metal',
  'virginia metal',
  'voidgaze',
  'welsh rock'
];
