export default [
  'adult standards',
  'african rock',
  'album rock',
  'ambient pop',
  'american post-rock',
  'anti-folk',
  'arab metal',
  'art punk',
  'athens indie',
  'australian alternative rock',
  'australian dance',
  'australian electropop',
  'australian metal',
  'australian post-rock',
  'australian psych',
  'australian rock',
  'austrian metal',
  'bardcore',
  'beatlesque',
  'belgian indie rock',
  'belgian new wave',
  'belgian post-rock',
  'belgian rock',
  'birmingham metal',
  'black thrash',
  'blackgaze',
  'boston metal',
  'boston rock',
  'bow pop',
  'boy band',
  'brazilian groove metal',
  'brazilian hardcore',
  'brazilian metal',
  'brazilian punk',
  'brazilian rock',
  'brazilian thrash metal',
  'brighton indie',
  'brill building pop',
  'brill building pop',
  'bristol indie',
  'british alternative rock',
  'british black metal',
  'british blues',
  'british invasion',
  'british post-rock',
  'british soul',
  'brostep',
  'bubblegum pop',
  'buffalo ny indie',
  'c86',
  'california hardcore',
  'canadian electropop',
  'canadian indie',
  'canadian metal',
  'canadian pop',
  'canadian rock',
  'canadian singer-songwriter',
  'candy pop',
  'chapman stick',
  'classic canadian rock',
  'classic uk pop',
  'comic',
  'complextro',
  'conscious hip hop',
  'cosmic american',
  'dalarna indie',
  'danish alternative rock',
  'danish metal',
  'danish rock',
  'dayton indie',
  'detroit rock',
  'dissonant death metal',
  'diva house',
  'dreamo',
  'dutch indie',
  'dutch metal',
  'dutch pop',
  'dutch rock',
  'early synthpop',
  'early us punk',
  'east coast hip hop',
  'ecm-style jazz',
  'ectofolk',
  'electropowerpop',
  'english indie rock',
  'europop',
  'filter house',
  'finnish alternative rock',
  'finnish death metal',
  'finnish doom metal',
  'finnish hard rock',
  'finnish melodeath',
  'finnish metal',
  'finnish power metal',
  'finnish progressive metal',
  'florida death metal',
  'flute rock',
  'french black metal',
  'french death metal',
  'french metal',
  'french post-rock',
  'french shoegaze',
  'gaian doom',
  'garage rock revival',
  'german alternative rock',
  'german dnb',
  'german hard rock',
  'german heavy metal',
  'german metal',
  'german pagan metal',
  'german power metal',
  'german rock',
  'german thrash metal',
  'girl group',
  'golden age hip hop',
  'granada indie',
  'greek metal',
  'heartland rock',
  'hi-nrg',
  'hungarian black metal',
  'hungarian metal',
  'hurdy-gurdy',
  'icelandic experimental',
  'icelandic pop',
  'icelandic post-punk',
  'icelandic rock',
  'icelandic singer-songwriter',
  'indian fusion',
  'indie poptimism',
  'irish rock',
  'irish singer-songwriter',
  'italian disco',
  'italian gothic metal',
  'italian gothic',
  'italian metal',
  'italian power metal',
  'jangle pop',
  'japanese classical',
  'japanese contemporary classical',
  'japanese post-rock',
  'japanese soundtrack',
  'korean instrumental',
  'la indie',
  'laboratorio',
  'lancashire indie',
  'lapland metal',
  'latin metal',
  'leicester indie',
  'lilith',
  'livetronica',
  'madchester',
  'magyar alternative',
  'manchester indie',
  'melancholia',
  'mellow gold',
  'memphis soul',
  'merseybeat',
  'metal mineiro',
  'metropopolis',
  'mexican classic rock',
  'mexican metal',
  'minneapolis sound',
  'modern dream pop',
  'musica aragonesa',
  'neue deutsche harte',
  'new romantic',
  'new wave of thrash metal',
  'nightrun',
  'ninja',
  'nordic folk metal',
  'nordic post-rock',
  'northern irish indie',
  'northern soul',
  'norwegian black metal',
  'norwegian metal',
  'norwegian pop',
  'nova mpb',
  'nu disco',
  'nu gaze',
  'nyhc',
  'nz metal',
  'nz pop',
  'old school hip hop',
  'olympia wa indie',
  'one-person band',
  'oriental metal',
  'oxford indie',
  'paisley underground',
  'palm desert scene',
  'philly indie',
  'pixie',
  'polish post-rock',
  'political hip hop',
  'power pop',
  'proto-metal',
  'protopunk',
  'protopunk',
  'pub rock',
  'quebec indie',
  'queens hip hop',
  'quiet storm',
  'rap metal',
  'reading indie',
  'riot grrrl',
  'rock en espanol',
  'roots rock',
  'rumba',
  'rune folk',
  'russian folk metal',
  'russian metal',
  'russian post-rock',
  'russian rave',
  'scottish indie',
  'scottish new wave',
  'scottish rock',
  'seattle indie',
  'seattle metal',
  'sheffield indie',
  'shimmer pop',
  'shred',
  'skate punk',
  'slavic metal',
  'slc indie',
  'sleaze rock',
  'solo wave',
  'sophisti-pop',
  'sophisti-pop',
  'south african rock',
  'southern soul',
  'spanish indie pop',
  'spanish rock',
  'speedrun',
  'stomp and holler',
  'sunshine pop',
  'supergroup',
  'swamp rock',
  'swedish alternative rock',
  'swedish death metal',
  'swedish electropop',
  'swedish garage rock',
  'swedish hard rock',
  'swedish indie pop',
  'swedish indie rock',
  'swedish melodeath',
  'swedish melodic rock',
  'swedish metal',
  'swedish pop',
  'swedish power metal',
  'swedish progressive metal',
  'swedish synth',
  'swedish synthpop',
  'swiss alternative rock',
  'swiss black metal',
  'swiss metal',
  'swiss rock',
  'texas blues',
  'texas metal',
  'tropical house',
  'tucson indie',
  'tucson indie',
  'turntablism',
  'uk doom metal',
  'uk metalcore',
  'uk post-punk',
  'uk post-punk',
  'us power metal',
  'vancouver metal',
  'virginia metal',
  'vocal jazz',
  'voidgaze',
  'welsh rock',
  'zolo'
];
