export const invalidGenres = [
  'american post-rock',
  'athens indie',
  'australian alternative rock',
  'australian dance',
  'australian electropop',
  'australian metal',
  'australian post-rock',
  'australian psych',
  'australian rock',
  'austrian metal',
  'belgian indie rock',
  'belgian new wave',
  'belgian post-rock',
  'belgian rock',
  'birmingham metal',
  'boston metal',
  'boston rock',
  'brazilian groove metal',
  'brazilian hardcore',
  'brazilian metal',
  'brazilian punk',
  'brazilian rock',
  'brazilian thrash metal',
  'brighton indie',
  'bristol indie',
  'british alternative rock',
  'british black metal',
  'british blues',
  'british invasion',
  'british post-rock',
  'british soul',
  'buffalo ny indie',
  'c86',
  'california hardcore',
  'canadian electropop',
  'canadian indie',
  'canadian metal',
  'canadian pop',
  'canadian rock',
  'canadian singer-songwriter',
  'classic canadian rock',
  'dalarna indie',
  'danish alternative rock',
  'danish metal',
  'danish rock',
  'detroit rock',
  'dissonant death metal',
  'dutch indie',
  'dutch metal',
  'dutch pop',
  'dutch rock',
  'english indie rock',
  'finnish alternative rock',
  'finnish death metal',
  'finnish doom metal',
  'finnish hard rock',
  'finnish melodeath',
  'finnish metal',
  'finnish power metal',
  'finnish progressive metal',
  'florida death metal',
  'french black metal',
  'french death metal',
  'french metal',
  'french post-rock',
  'french shoegaze',
  'german alternative rock',
  'german dnb',
  'german hard rock',
  'german heavy metal',
  'german metal',
  'german pagan metal',
  'german power metal',
  'german rock',
  'german thrash metal',
  'greek metal',
  'hungarian black metal',
  'hungarian metal',
  'icelandic experimental',
  'icelandic pop',
  'icelandic post-punk',
  'icelandic rock',
  'icelandic singer-songwriter',
  'indian fusion',
  'irish rock',
  'irish singer-songwriter',
  'israeli metal',
  'italian disco',
  'italian gothic',
  'italian gothic metal',
  'italian metal',
  'italian power metal',
  'japanese classical',
  'japanese contemporary classical',
  'japanese post-rock',
  'japanese soundtrack',
  'korean instrumental',
  'lancashire indie',
  'lapland metal',
  'leicester indie',
  'magyar alternative',
  'manchester indie',
  'memphis soul',
  'merseybeat',
  'metal mineiro',
  'mexican classic rock',
  'mexican metal',
  'minneapolis sound',
  'musica aragonesa',
  'neue deutsche harte',
  'nordic folk metal',
  'nordic post-rock',
  'northern irish indie',
  'northern soul',
  'norwegian black metal',
  'norwegian metal',
  'norwegian pop',
  'nz metal',
  'nz pop',
  'oriental metal',
  'oxford indie',
  'polish post-rock',
  'quebec indie',
  'queens hip hop',
  'rock en espanol',
  'russian folk metal',
  'russian metal',
  'russian post-rock',
  'russian rave',
  'scottish indie',
  'scottish new wave',
  'scottish rock',
  'seattle indie',
  'seattle metal',
  'sheffield indie',
  'slavic metal',
  'south african rock',
  'spanish indie pop',
  'spanish rock',
  'swedish alternative rock',
  'swedish death metal',
  'swedish electropop',
  'swedish garage rock',
  'swedish hard rock',
  'swedish indie pop',
  'swedish indie rock',
  'swedish melodeath',
  'swedish melodic rock',
  'swedish metal',
  'swedish pop',
  'swedish power metal',
  'swedish progressive metal',
  'swedish synth',
  'swedish synthpop',
  'swiss alternative rock',
  'swiss black metal',
  'swiss metal',
  'swiss rock',
  'texas blues',
  'texas metal',
  'vancouver metal'
];
